MovieRentalApp/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;

namespace MovieRentalApp.Models
{
    public class Movie
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(100)]
        public string Title { get; set; }
        [Required]
        [MaxLength(255)]
        public string ShortDescription { get; set; }
        public string ImageUrl { get; set; }
        public DateTime ReleaseDate { get; set; }
        public DateTime CreatedAt { get; set; }

        public virtual Director Director { get; set; }
        public int DirectorId { get; set; }

        public virtual Customer Borrower { get; set; }
        [AllowNull]
        public int? BorrowerId { get; set; }
    }
}

MovieRentalApp/ViewModels/MovieViewModel.cs
using MovieRentalApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieRentalApp.ViewModels
{
    public class MovieViewModel
    {
        public Movie Movie { get; set; }
        public IEnumerable<Director> Directors { get; set; }
    }
}

MovieRentalApp/Controllers/DirectorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieRentalApp.Data.Interfaces;
using MovieRentalApp.Models;
using MovieRentalApp.ViewModels;

namespace MovieRentalApp.Controllers
{
    public class DirectorController : Controller
    {
        private readonly IDirectorRepository _directorRepository;

        public DirectorController(IDirectorRepository directorRepository)
        {
            _directorRepository = directorRepository;
        }

        public IActionResult index()
        {
            var directors = _directorRepository.GetAllWhitMovies();

            if (directors.Count() == 0) return View("Empty");

            return View(directors);
        }

        public IActionResult Update(int id)
        {
            var director = _directorRepository.GetById(id);

            if (director == null) return NotFound();

            return View(director);
        }

        [HttpPost]
        public IActionResult Update(Director director)
        {
            if (!ModelState.IsValid)
            {
                return View(director);
            }

            _directorRepository.Update(director);

            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            var viewModel = new CreateDirectorViewModel
            { Referer = Request.Headers["Referer"].ToString() };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Create(CreateDirectorViewModel directorVM)
        {
            if (!ModelState.IsValid)
            {
                return View(directorVM);
            }

            directorVM.Director.CreatedAt = DateTime.Now;
            _directorRepository.Create(directorVM.Director);

            if (!String.IsNullOrEmpty(directorVM.Referer))
            {
                return Redirect(directorVM.Referer);
            }

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var director = _directorRepository.GetById(id);

            _directorRepository.Delete(director);

            return RedirectToAction("Index");
        }
    }
}

MovieRentalApp/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MovieRentalApp.Data.Interfaces;
using MovieRentalApp.Models;
using MovieRentalApp.ViewModels;

namespace MovieRentalApp.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepository _movieRepository;
        private readonly IDirectorRepository _directorRepository;

        public MovieController(IMovieRepository movieRepository, IDirectorRepository directorRepository)
        {
            _movieRepository = movieRepository;
            _directorRepository = directorRepository;
        }

        public IActionResult Index(int? directorId, int? borrowerId)
        {
            if (directorId == null && borrowerId == null)
            {
                var movie = _movieRepository.GetAllWhitDirector();
                return CheckMovies(movie);
            }
            else if (directorId != null)
            {
                // filter by director id
                var director = _directorRepository.GetWhitMovies((int)directorId);

                if (director.Movies.Count() == 0)
                {
                    return View("EmptyDirector", director);
                }
                else
                {
                    return View(director.Movies);
                }
            }
            else if (borrowerId != null)
            {
                // filter by customer id
                var movies = _movieRepository.FindWhitDirectorAndCustomer(m => m.BorrowerId == borrowerId);
                // check customer movies
                return CheckMovies(movies);
            }
            else
            {
                throw new ArgumentException();
            }
        }

        public IActionResult Create()
        {
            var movieVM = new MovieViewModel()
            {
                Directors = _directorRepository.GetAll()
            };
            return View(movieVM);
        }

        [HttpPost]
        public IActionResult Create(MovieViewModel movieViewModel)
        {
            if (!ModelState.IsValid)
            {
                movieViewModel.Directors = _directorRepository.GetAll();
                return View(movieViewModel);
            }

            movieViewModel.Movie.CreatedAt = DateTime.Now;
            _movieRepository.Create(movieViewModel.Movie);

            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            var movieVM = new MovieViewModel()
            {
                Movie = _movieRepository.GetById(id),
                Directors = _directorRepository.GetAll()
            };
            return View(movieVM);
        }

        [HttpPost]
        public IActionResult Update(MovieViewModel movieViewModel)
        {
            if (!ModelState.IsValid)
            {
                movieViewModel.Directors = _directorRepository.GetAll();
                return View(movieViewModel);
            }

            _movieRepository.Update(movieViewModel.Movie);

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var movie = _movieRepository.GetById(id);

            _movieRepository.Delete(movie);

            return RedirectToAction("Index");
        }

        public IActionResult CheckMovies(IEnumerable<Movie> movie)
        {
            if (movie.Count() == 0)
            {
                return View("Empty");
            }
            else
            {
                return View(movie);
            }
        }
    }
}

MovieRentalApp/Views/Movie/Create.cshtml
@model MovieViewModel

<div class="row">
    <form asp-controller="Movie" asp-action="Create" method="post" class="col-md-8">
        <h3 class="col-md-12 my-5">Create new movie</h3>

        <div class="form-group">
            <label asp-for="Movie.Director" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                @Html.DropDownListFor(m => m.Movie.DirectorId,
                                       new SelectList(Model.Directors.Select(x => new { Value = x.Id, Text = x.Name }), "Value", "Text"), "Select a Director",
                                       htmlAttributes: new { @class = "form-control border-input" })
                <span asp-validation-for="Movie.Director" class="text-danger"></span>
            </div>

            <div class="col-md-3 mt-3">
                <a class="btn btn-success" asp-controller="Director" asp-action="Create">Create a Director</a>
            </div>

        </div>
        <div class="form-group">
            <label asp-for="Movie.Title" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Movie.Title" class="form-control" placeholder="Enter movie title" />
                <span asp-validation-for="Movie.Title" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Movie.ShortDescription" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Movie.ShortDescription" class="form-control" placeholder="Enter movie short description here" />
                <span asp-validation-for="Movie.ShortDescription" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Movie.ImageUrl" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Movie.ImageUrl" class="form-control" />
                <span asp-validation-for="Movie.ImageUrl" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="btn-group col-md-6 mt-3">
                <input class="btn btn-primary col-md-3 mr-3" type="submit" value="Return" asp-controller="Movie" asp-action="Index" />
                <input class="btn btn-success col-md-3" type="submit" value="Create" />
            </div>
        </div>
    </form>
</div>

MovieRentalApp/Views/Movie/Empty.cshtml
<a class="btn btn-success mt-5" asp-controller="Movie" asp-action="Create">Create new movie</a>

<h2>There are no movies.</h2>

MovieRentalApp/Views/Movie/EmptyDirector.cshtml
@model Director

<h2>Director @Model.Name has no movies.</h2>

MovieRentalApp/Views/Movie/Index.cshtml
@model IEnumerable<Movie>

<a class="btn btn-success mt-5" asp-controller="Movie" asp-action="Create">Create new movie</a>

<table class="table table-striped table-hover my-5 table-borderless">
    <thead>
        <tr>
            <th>Img</th>
            <th>ID</th>
            <th>Title</th>
            <th>Year</th>
            <th>Directors name</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Movie movie in Model)
        {
        <tr>
            <td><img src="@movie.ImageUrl" alt="Movie picture" style="width: 50px; height:50px;"></td>
            <td>@movie.Id</td>
            <td>@movie.Title</td>
            <td>@movie.ReleaseDate</td>
            <td>@movie.Director.Name</td>
            <td>
                <a class="btn btn-info" asp-controller="Movie" asp-action="Update" asp-route-id="@movie.Id">Edit</a>
                <a class="btn btn-danger" asp-controller="Movie" asp-action="Delete" asp-route-id="@movie.Id" asp-route-authorId="@ViewBag.AuthorId">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

MovieRentalApp/Views/Movie/Update.cshtml
@model MovieViewModel

<div class="row">

    <form asp-controller="Movie" asp-action="Update" method="post" class="col-md-8">
        <h3 class="col-md-12 my-5">Update movie</h3>
        @Html.HiddenFor(m => Model.Movie.Id)
        @Html.HiddenFor(m => Model.Movie.CreatedAt)
        <div class="form-group">
            <label asp-for="Movie.Director" class="col-md-2 control-label"></label>
            <div class="col-md-6">

                @Html.DropDownListFor(m => m.Movie.DirectorId,
                                                  new SelectList(Model.Directors.Select(x => new { Value = x.Id, Text = x.Name }), "Value", "Text"),
                                                  htmlAttributes: new { @class = "form-control border-input" })
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Movie.Title" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Movie.Title" class="form-control" placeholder="Enter movie title" />
                <span asp-validation-for="Movie.Title" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Movie.ShortDescription" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Movie.ShortDescription" class="form-control" placeholder="Enter movie short description here" />
                <span asp-validation-for="Movie.ShortDescription" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Movie.ImageUrl" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Movie.ImageUrl" class="form-control" />
                <span asp-validation-for="Movie.ImageUrl" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="btn-group col-md-6 mt-3">
                <input class="btn btn-primary col-md-3 mr-3" type="submit" value="Return" asp-controller="Movie" asp-action="Index" />
                <input class="btn btn-success col-md-3" type="submit" value="Update" />
            </div>
        </div>
    </form>
</div>