MovieRentalApp/Controllers/CustomerController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using MovieRentalApp.Data.Interfaces;
using MovieRentalApp.Models;
using MovieRentalApp.ViewModels;

namespace MovieRentalApp.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerRepository _customerRepository;
        private readonly IMovieRepository _movieRepository;

        public CustomerController(ICustomerRepository customerRepository, IMovieRepository movieRepository)
        {
            _customerRepository = customerRepository;
            _movieRepository = movieRepository;
        }

        public IActionResult Index()
        {
            var customerVM = new List<CustomerViewModel>();

            var customers = _customerRepository.GetAll();

            if (customers.Count() == 0)
            {
                return View("Empty");
            }

            foreach (var customer in customers)
            {
                customerVM.Add(new CustomerViewModel
                {
                    Customer = customer,
                    MovieCount = _movieRepository.Count(x => x.BorrowerId == customer.Id)
                });
            }

            return View(customerVM);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Customer customer)
        {
            if (!ModelState.IsValid)
            {
                return View(customer);
            }

            customer.CreatedAt = DateAndTime.Now;
            _customerRepository.Create(customer);

            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            var customer = _customerRepository.GetById(id);

            return View(customer);
        }

        [HttpPost]
        public IActionResult Update(Customer customer)
        {
            if (!ModelState.IsValid)
            {
                return View(customer);
            }

            _customerRepository.Update(customer);

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var customer = _customerRepository.GetById(id);

            _customerRepository.Delete(customer);

            return RedirectToAction("Index");
        }
    }
}

MovieRentalApp/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MovieRentalApp.Data.Interfaces;
using MovieRentalApp.Models;
using MovieRentalApp.ViewModels;

namespace MovieRentalApp.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepository _movieRepository;
        private readonly IDirectorRepository _directorRepository;

        public MovieController(IMovieRepository movieRepository, IDirectorRepository directorRepository)
        {
            _movieRepository = movieRepository;
            _directorRepository = directorRepository;
        }

        public IActionResult Index(int? directorId, int? borrowerId)
        {
            if (directorId == null && borrowerId == null)
            {
                var movie = _movieRepository.GetAllWhitDirector();
                return CheckMovies(movie);
            }
            else if (directorId != null)
            {
                // filter by director id
                var director = _directorRepository.GetWhitMovies((int)directorId);

                if (director.Movies.Count() == 0)
                {
                    return View("EmptyDirector", director);
                }
                else
                {
                    return View(director.Movies);
                }
            }
            else if (borrowerId != null)
            {
                // filter by customer id
                var movies = _movieRepository.FindWhitDirectorAndCustomer(m => m.BorrowerId == borrowerId);
                // check customer movies
                return CheckMovies(movies);
            }
            else
            {
                throw new ArgumentException();
            }
        }

        public IActionResult Create()
        {
            var movieVM = new MovieViewModel()
            {
                Directors = _directorRepository.GetAll()
            };
            return View(movieVM);
        }

        [HttpPost]
        public IActionResult Create(MovieViewModel movieViewModel)
        {
            if (!ModelState.IsValid)
            {
                movieViewModel.Directors = _directorRepository.GetAll();
                return View(movieViewModel);
            }

            movieViewModel.Movie.CreatedAt = DateTime.Now;
            _movieRepository.Create(movieViewModel.Movie);

            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            var movieVM = new MovieViewModel()
            {
                Movie = _movieRepository.GetById(id),
                Directors = _directorRepository.GetAll()
            };
            return View(movieVM);
        }

        [HttpPost]
        public IActionResult Update(MovieViewModel movieViewModel)
        {
            if (!ModelState.IsValid)
            {
                movieViewModel.Directors = _directorRepository.GetAll();
                return View(movieViewModel);
            }

            _movieRepository.Update(movieViewModel.Movie);

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var movie = _movieRepository.GetById(id);

            _movieRepository.Delete(movie);

            return RedirectToAction("Index");
        }

        public IActionResult CheckMovies(IEnumerable<Movie> movie)
        {
            if (movie.Count() == 0)
            {
                return View("Empty");
            }
            else
            {
                return View(movie);
            }
        }
    }
}

MovieRentalApp/Controllers/RentalController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MovieRentalApp.Data.Interfaces;
using MovieRentalApp.ViewModels;

namespace MovieRentalApp.Controllers
{
    public class RentalController : Controller
    {
        private readonly IMovieRepository _movieRepository;
        private readonly ICustomerRepository _customerRepository;

        public RentalController(IMovieRepository movieRepository, ICustomerRepository customerRepository)
        {
            _movieRepository = movieRepository;
            _customerRepository = customerRepository;
        }

        public IActionResult Index()
        {
            var availableMovies = _movieRepository.FindWhitDirector(x => x.BorrowerId == null);
            if (availableMovies.Count() == 0)
            {
                return View("Empty");
            }
            else
            {
                return View(availableMovies);
            }
        }

        public IActionResult RentMovie(int movieId)
        {
            var rentVM = new RentalViewModel()
            {
                Movie = _movieRepository.GetById(movieId),
                Customers = _customerRepository.GetAll()
            };
            return View(rentVM);
        }

        [HttpPost]
        public IActionResult RentMovie(RentalViewModel rentalViewModel)
        {
            var movie = _movieRepository.GetById(rentalViewModel.Movie.Id);

            var customer = _customerRepository.GetById(rentalViewModel.Movie.BorrowerId);

            movie.Borrower = customer;

            _movieRepository.Update(movie);

            return RedirectToAction("Index");
        }
    }
}

MovieRentalApp/Controllers/ReturnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieRentalApp.Data.Interfaces;

namespace MovieRentalApp.Controllers
{
    public class ReturnController : Controller
    {
        private readonly IMovieRepository _movieRepository;
        private readonly ICustomerRepository _customerRepository;

        public ReturnController(IMovieRepository movieRepository, ICustomerRepository customerRepository)
        {
            _movieRepository = movieRepository;
            _customerRepository = customerRepository;
        }

        public IActionResult Index()
        {
            // rented movies
            var rentedMovies = _movieRepository.FindWhitDirectorAndCustomer(x => x.BorrowerId != null);

            if (rentedMovies == null || rentedMovies.ToList().Count() == 0)
            {
                return View("Empty");
            }
            return View(rentedMovies);
        }

        public IActionResult ReturnMovie(int movieId)
        {
            var movie = _movieRepository.GetById(movieId);
            movie.Borrower = null;
            movie.BorrowerId = null;

            _movieRepository.Update(movie);

            return RedirectToAction("Index");
        }
    }
}

MovieRentalApp/Views/Shared/DirectorPartial.cshtml
@model Director

    <div class="col-md-4">
        <div class="card mr-5 mb-5">
            <div class="card-header">
                <h5>@Model.Name</h5>
            </div>
            <div class="card-body">
                <h2 class="card-title">Movie count: @Model.Movies?.Count</h2>
                <div class="btn-group">
                    <a class="btn btn-primary mr-3" asp-controller="Movie" asp-action="Index" asp-route-authorId="@Model.Id">Movie list</a>
                    <a class="btn btn-info mr-3" asp-controller="Director" asp-action="Update" asp-route-id="@Model.Id">Edit</a>
                    <a class="btn btn-danger" asp-controller="Director" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
                </div>
            </div>
        </div>
    </div>

MovieRentalApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieRentalApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieRentalApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Director" asp-action="Index">Director</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Movie" asp-action="Index">Movie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Rental" asp-action="Index">Rental</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Return" asp-action="Index">Return</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MovieRentalApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>